// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CheckConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function GetContinuousStats() {
  return window['go']['main']['App']['GetContinuousStats']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportConfig(arg1, arg2) {
  return window['go']['main']['App']['ImportConfig'](arg1, arg2);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function IsContinuousRunning() {
  return window['go']['main']['App']['IsContinuousRunning']();
}

export function OpenGitHub() {
  return window['go']['main']['App']['OpenGitHub']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}

export function SelectCACertificate() {
  return window['go']['main']['App']['SelectCACertificate']();
}

export function SelectClientCertificate() {
  return window['go']['main']['App']['SelectClientCertificate']();
}

export function SelectClientKey() {
  return window['go']['main']['App']['SelectClientKey']();
}

export function SendSyslogMessages(arg1) {
  return window['go']['main']['App']['SendSyslogMessages'](arg1);
}

export function StartContinuousSend(arg1) {
  return window['go']['main']['App']['StartContinuousSend'](arg1);
}

export function StopContinuousSend() {
  return window['go']['main']['App']['StopContinuousSend']();
}
