// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenGitHub() {
  return window['go']['main']['App']['OpenGitHub']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SetServices(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetServices'](arg1, arg2, arg3);
}
