// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckConnection(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:string,arg7:string,arg8:string):Promise<boolean>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ExportConfig():Promise<string>;

export function GetContinuousStats():Promise<main.ContinuousStats>;

export function GetProfiles():Promise<Array<main.ConnectionProfile>>;

export function GetTemplates():Promise<Array<main.LogTemplate>>;

export function GetVersion():Promise<string>;

export function ImportConfig(arg1:string,arg2:boolean):Promise<void>;

export function ImportLogFile(arg1:string):Promise<main.BatchImportResult>;

export function IsConnected():Promise<boolean>;

export function IsContinuousRunning():Promise<boolean>;

export function OpenGitHub():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveProfile(arg1:main.ConnectionProfile):Promise<main.ConnectionProfile>;

export function SaveTemplate(arg1:main.LogTemplate):Promise<main.LogTemplate>;

export function SelectCACertificate():Promise<string>;

export function SelectClientCertificate():Promise<string>;

export function SelectClientKey():Promise<string>;

export function SelectLogFile():Promise<string>;

export function SendSyslogMessages(arg1:main.SyslogConfig):Promise<main.SyslogResponse>;

export function StartContinuousSend(arg1:main.ContinuousSendConfig):Promise<void>;

export function StopContinuousSend():Promise<void>;
