// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckConnection(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function Disconnect():Promise<void>;

export function SendSyslogMessages(arg1:main.SyslogConfig):Promise<main.SyslogResponse>;
