// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CheckConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SelectCACertificate() {
  return window['go']['main']['App']['SelectCACertificate']();
}

export function SelectClientCertificate() {
  return window['go']['main']['App']['SelectClientCertificate']();
}

export function SelectClientKey() {
  return window['go']['main']['App']['SelectClientKey']();
}

export function SendSyslogMessages(arg1) {
  return window['go']['main']['App']['SendSyslogMessages'](arg1);
}
