// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportLogFile(arg1) {
  return window['go']['main']['BatchImportService']['ImportLogFile'](arg1);
}

export function SelectLogFile() {
  return window['go']['main']['BatchImportService']['SelectLogFile']();
}

export function SetContext(arg1) {
  return window['go']['main']['BatchImportService']['SetContext'](arg1);
}
