// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function ImportLogFile(arg1:string):Promise<main.BatchImportResult>;

export function SelectLogFile():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
