// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {net} from '../models';
import {context} from '../models';

export function CheckConnection(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:string,arg7:string,arg8:string):Promise<boolean>;

export function Disconnect():Promise<void>;

export function GetConnection():Promise<net.Conn>;

export function IsConnected():Promise<boolean>;

export function SelectCACertificate():Promise<string>;

export function SelectClientCertificate():Promise<string>;

export function SelectClientKey():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
