// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['ConnectionService']['CheckConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function Disconnect() {
  return window['go']['main']['ConnectionService']['Disconnect']();
}

export function GetConnection() {
  return window['go']['main']['ConnectionService']['GetConnection']();
}

export function IsConnected() {
  return window['go']['main']['ConnectionService']['IsConnected']();
}

export function SelectCACertificate() {
  return window['go']['main']['ConnectionService']['SelectCACertificate']();
}

export function SelectClientCertificate() {
  return window['go']['main']['ConnectionService']['SelectClientCertificate']();
}

export function SelectClientKey() {
  return window['go']['main']['ConnectionService']['SelectClientKey']();
}

export function SetContext(arg1) {
  return window['go']['main']['ConnectionService']['SetContext'](arg1);
}
