// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['main']['ProfileService']['DeleteProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['ProfileService']['GetProfiles']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['ProfileService']['SaveProfile'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['ProfileService']['SetContext'](arg1);
}
