// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function DeleteProfile(arg1:string):Promise<void>;

export function GetProfiles():Promise<Array<main.ConnectionProfile>>;

export function SaveProfile(arg1:main.ConnectionProfile):Promise<main.ConnectionProfile>;

export function SetContext(arg1:context.Context):Promise<void>;
