// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function GetContinuousStats():Promise<main.ContinuousStats>;

export function IsContinuousRunning():Promise<boolean>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartContinuousSend(arg1:main.ContinuousSendConfig):Promise<void>;

export function StopContinuousSend():Promise<void>;
