// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContinuousStats() {
  return window['go']['main']['StressTestService']['GetContinuousStats']();
}

export function IsContinuousRunning() {
  return window['go']['main']['StressTestService']['IsContinuousRunning']();
}

export function SetContext(arg1) {
  return window['go']['main']['StressTestService']['SetContext'](arg1);
}

export function StartContinuousSend(arg1) {
  return window['go']['main']['StressTestService']['StartContinuousSend'](arg1);
}

export function StopContinuousSend() {
  return window['go']['main']['StressTestService']['StopContinuousSend']();
}
