// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendSyslogMessages(arg1) {
  return window['go']['main']['SyslogService']['SendSyslogMessages'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['SyslogService']['SetContext'](arg1);
}
