// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function SendSyslogMessages(arg1:main.SyslogConfig):Promise<main.SyslogResponse>;

export function SetContext(arg1:context.Context):Promise<void>;
