// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTemplate(arg1) {
  return window['go']['main']['TemplateService']['DeleteTemplate'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['TemplateService']['ExportConfig']();
}

export function GetTemplates() {
  return window['go']['main']['TemplateService']['GetTemplates']();
}

export function ImportConfig(arg1, arg2) {
  return window['go']['main']['TemplateService']['ImportConfig'](arg1, arg2);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['TemplateService']['SaveTemplate'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['TemplateService']['SetContext'](arg1);
}
