// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function DeleteTemplate(arg1:string):Promise<void>;

export function ExportConfig():Promise<string>;

export function GetTemplates():Promise<Array<main.LogTemplate>>;

export function ImportConfig(arg1:string,arg2:boolean):Promise<void>;

export function SaveTemplate(arg1:main.LogTemplate):Promise<main.LogTemplate>;

export function SetContext(arg1:context.Context):Promise<void>;
