name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    # Backend Linting
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Lint Go code
      run: go vet ./...

    # Frontend Linting
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./client

    - name: Lint frontend code
      run: npm run lint
      working-directory: ./client

    # Build Steps
    - name: Build backend
      run: go build ./...

    - name: Build frontend
      run: npm run build
      working-directory: ./client